### ISSUE TITLE
Region GPU not working on Apple Silicon

### ISSUE THREAD

**Issue by cronicstate** [slaytostay/region-locker#13]
When enabling the Region GPU, it automatically disables itself.

Normal GPU plugin, and 117 GPU plugins work fine.

I've also tried manually enabling the Region GPU option in settings.properties, and launching Runelite... But no luck.

**Comment by cronicstate** [comment]
Yeah, made sure Region Locker is on. Also tried uninstalling runelite and removing all references in case of a bad install... No dice.

I'm on MacOS Monterey 12.3

**Comment by slaytostay** [comment]
Can I have a look at your log files (specifically `~/.runelite/logs/client.log`)? If you want we can continue this in Discord DMs, I tend to respond quicker there. I am Slay to Stay in the [Chunk Discord](https://discord.gg/JrHCmAFN).
