### ISSUE TITLE
Goal Tracker: Edit & rearrange tasks (Feature Request)

### ISSUE THREAD

**Issue by Marstead** [slaytostay/region-locker#16]
Right now, the user can only add or delete tasks, but cannot edit existing tasks or change the order they appear in the plugin. In addition, added chunks cannot be re-ordered or sorted. You can edit or re-order things by exporting Goals.json and moving things around, but it would be much more convenient to be able to do this inside the tool.

**Comment by aHooder** [comment]
Added in 4c8238389a70247780afa75e7944fff39d53b392
