### ISSUE TITLE
Goal Tracker: Hide completed Chunks setting (Feature Request)

### ISSUE THREAD

**Issue by Marstead** [slaytostay/region-locker#18]
Right now, each chunk can be collapsed or uncollapsed, which helps to sort through the list a bit. But if you have a lot of chunks to track, it can become cumbersome to scroll through all of the collapsed completed chunks. It would be helpful to have a setting in the Plugin Options for "Hide Completed Chunks" which causes any chunk that is marked complete to be hidden from the Goal Tracker list until this option is unchecked.

_(Thank you for making this plugin, it is absolutely amazing and completely enables the restricted account I am building. The plugin as-is is really great, but the handful of feature requests I have submitted would make it even better!)_

**Comment by slaytostay** [comment]
Thank you for kind comment and the feature requests :) They are all great suggestions! However, I'm currently not really in the position to develop any extra features for this plugin.

I'm not really sure, but I think [Chunk Picker v2](https://source-chunk.github.io/chunk-picker-v2/) has a some of these features and the developer (Source Chunk) is very active on the [Chunk Discord](https://discord.gg/QJpbvRJM). So you can try if he is able to implement some of these. Otherwise, I'm afraid it will take a while before I can get to work on them.

**Comment by Marstead** [comment]
Thanks again so much for the plugin! I understand if you don't have very much time to work on this. I reached out to Source Chunk and it looks like his plate is pretty full too.

Just out of curiosity, do you know why Emojis break on import/export? I'd like to use emojis to indicate categories of tasks (like 💀for "Slay" tasks or ⛏ for "Mine" tasks) and they work when entered into the application directly. However, they break when exported (they export as a "?". If entered in the JSON file directly, they look fine in the JSON but them import as a string of special characters.

**Comment by slaytostay** [comment]
I'm not too sure, the plugin uses gson for the import and export of the config files. After quickly looking it up, gson may not have the best support for Unicode characters.

**Comment by Marstead** [comment]
Hey again! While I wasn't able to get SourceChunk to help out, one of my viewers saw this emoji encoding issue and submitted a pull request to fix the import/export. Any chance you can merge it? Thank you!

**Comment by slaytostay** [comment]
Sorry, my internet access is limited atm as I am in the process of moving to a very remote area. But it should be fixed once RuneLite accepts it :)

Thanks for getting your commubity involved! Pull requests are possibly the only way these features will be implemented in the near future

**Comment by aHooder** [comment]
Added in 8b7e2a128bc80d23c398a1f935a59ffb1c25276f
