### ISSUE TITLE
Change name of "Goal Tracker" subplugin to prevent Runelite Conflict

### ISSUE THREAD

**Issue by Marstead** [slaytostay/region-locker#22]
Region Locker also installs a subplugin called "Goal Tracker" for tracking goals related to chunks. There is a totally separate plugin also called "Goal Tracker" on the Plugin Hub. Unfortunately, if both Region Locker and the separate Goal Tracker plugin are installed, both of them break. To fix this, one or the other will need to be renamed. (Also opening this issue under the Goal Tracker Plugin repo).

**Comment by Marstead** [comment]
Hey there, just wanted to see if there's any chance this can get a hotfix -- even just changing the subplugin to "Region-Goal Tracker" would fix the conflict. Thank you!

**Comment by slaytostay** [comment]
So sorry! Forgot to act on this when I first saw it, pull request made :)
