### ISSUE TITLE
Logging into the game with "Region Locker" = OFF and "Region GPU" = ON crashes RuneLite

### ISSUE THREAD

**Issue by Lorentary** [slaytostay/region-locker#27]
The client can start, but clicking the "Play Now" button (RuneLite through Jagex Client) crashes the game with a generic error "Something went wrong" type error message

**Comment by aHooder** [comment]
This doesn't happen for me on the version that is pending review currently. Once the updated plugin is added, can you check if this is still happening for you?
You can follow this PR for updates on the review: https://github.com/runelite/plugin-hub/pull/4073
