### ISSUE TITLE
Conflicts with regular GPU plugin and Chunk GPU plugin

### ISSUE THREAD

**Issue by DjoanG** [slaytostay/region-locker#29]
I've been using the new profiles on Runelite and noticed an issue when switching from an account that has the Chunk GPU plugin enabled to one that normally has the regular GPU plugin enabled. A problem occurs where the account I'm switching to has the regular GPU plugin disabled (normally always on) and I'm not allowed to enable it again until I reload my Runelite and it launches on the correct profile without Chunk GPU enabled.

**Comment by aHooder** [comment]
That sounds like a core RuneLite bug, but I'll look into it.

**Comment by aHooder** [comment]
This doesn't seem to happen anymore. Can you check if this is still happening for you?

**Comment by DjoanG** [comment]
Can't check it atm as the region-locker plugin still isn't back up on RuneLite for me, as it's had some issues latetly.

**Comment by aHooder** [comment]
Yeah, sorry. We'll have to wait for this PR still: https://github.com/runelite/plugin-hub/pull/4073

**Comment by DjoanG** [comment]
Seems like this issue has been fixed after the plugin has come back online
