### ISSUE TITLE
Region Locker plugin broken with 03/15/23 RuneLite Update

### ISSUE THREAD

**Issue by Marstead** [slaytostay/region-locker#30]
Hello! The Region Locker plugin failed to build with the 03/15/23 RuneLite update. I know this project has been off the radar for some time, but several chunk accounts have become dependent on this plugin for the game-mode. If you get a chance to fix and redeploy it we'd all appreciate it very much!

**Comment by slaytostay** [comment]
Of course, I'm on it :+1:

**Comment by betafalconrecon** [comment]
Thanks for being willing to update it, we definitely do appreciate it! Any rough eta on when it will be available?

Thanks again, slaytostay

**Comment by slaytostay** [comment]
It's up to the RuneLite devs now https://github.com/runelite/plugin-hub/pull/4059

**Comment by Marstead** [comment]
> 

Thank you so much for your time on this one. I know you don't have a ton of time to maintain this and mentioned looking for someone to take over in the link. Maybe you could ask the Chunk Picker V2 Discord to see if anyone would be interested? Lots of active chunkers over there, I assume at least one of them would be able to help! https://discord.gg/TnYjVrZ7

**Comment by aHooder** [comment]
slaytostay's original patch would have fixed it, but we've submitted a new patch here that you can follow: https://github.com/runelite/plugin-hub/pull/4073
I'll try to maintain this from now on when slaytostay isn't able to.

**Comment by Marstead** [comment]
> slaytostay's original patch would have fixed it, but we've submitted a new patch here that you can follow: [runelite/plugin-hub#4073](https://github.com/runelite/plugin-hub/pull/4073) I'll try to maintain this from now on when slaytostay isn't able to.

Thank you both so much! ❤️ There are a couple lingering issues I may open in that case (there's still a naming convention conflict with the Goal Tracker plugin, for example) but just getting the base plugin back is huge. Thank you both again!

**Comment by raccoondad96** [comment]
Sorry, I tried to follow the updates to the plugins current state as the conversation here unfolded but I still don't follow. Is the plugin fixed or approved by Runelite now? I still cannot find the plugin when I search region locker on the Runelite launcher. 
Thank you so much for your time developing this plugin, I am asking because it is a main component to my Youtube series :)

**Comment by aHooder** [comment]
It's currently pending review by RuneLite.
