### ISSUE TITLE
Locked Chunk Shader not functioning with Cerberus' Lair

### ISSUE THREAD

**Issue by source-chunk** [slaytostay/region-locker#37]
With the Region Locker and Region Locker GPU plugins on, and with the `Unlock underground` and `Unlock realms` options turned on, Cerberus' Lair (both where the Key Master is and the boss lair itself) is still greyed out with the Locked Chunk Shader.

The expected behavior of this would be that, since Cerberus' Lair is not an aboveground chunk, that either the `Unlock underground` option or the `Unlock realms` option would prevent the Shader from being used in this case.

**Comment by aHooder** [comment]
Fixed in 5ccd6569a9e7bea4226cba5f1f537b5be15e1e6f. Thanks for reporting :slightly_smiling_face:
