### ISSUE TITLE
Compatability with hiding p2p areas for f2p users

### ISSUE THREAD

**Issue by blakegearin** [slaytostay/region-locker#9]
Hey there, I found your plugin today and it reminded me of this issue I logged: runelite/runelite#12599

Do you think your plugin could support something like this?

**Comment by slaytostay** [comment]
Could be kinda cool, but I don't think it's in the scope of this project unless someone compiles a list of chunks that contain free to play content.

**Comment by slaytostay** [comment]
Closing until such a set becomes available.
